// App data
type SET_APP_DATA = 'SET_APP_DATA';
type ADD_GOAL = 'ADD_GOAL';
type REMOVE_GOAL = 'REMOVE_GOAL';
type EDIT_GOAL = 'EDIT_GOAL';

// User data
type SET_USER_DATA = 'SET_USER_DATA';

export type { SET_APP_DATA, ADD_GOAL, REMOVE_GOAL, EDIT_GOAL, SET_USER_DATA };
